### ISSUE TITLE
Colour code of cable

### ISSUE THREAD

**Issue by Rudertier** [Miceuz/i2c-moisture-sensor#23]
Hi,
first of all, thanks for the quick delivery. I've ordered one rugged version of the sensor and I'm eager to play around with the device.
Having the rugged version, I can not tell which cable is used for what, and I'm afraid of trying it out on my own. 
Any advice?
![2018-04-05 08 38 32](https://user-images.githubusercontent.com/19547127/38351119-76f03c72-38ae-11e8-9737-8b40406f289d.jpg)

**Comment by mindforger** [comment]
pulled from tindie

>Rugged version
Pre-coated version is available since December 2016. The sensor is coated in epoxy resin, cured and additionally protected by adhesive-lined heat shrink. The 1m (3 feet) long cable is pre-soldered. Light sensor is covered by heatshrink, so the light reading will always report total darkness.
The pinout of the rugged version (with white cable):
    RED - VCC
    BLACK - GND
    BLUE or GREEN- SDA
    YELLOW - SCK
Shield is not grounded on the sensor end and must be grounded on the master end.

**Comment by Rudertier** [comment]
Thank's a lot, some how I did not find it.
